[package]
name = "opensi-editor"
version = "0.1.0"
authors = ["snpefk <snpefk@gmail.com>"]
edition = "2018"

[dependencies]
opensi = { version = "*", path = "../opensi" }

gtk = "^0.8.0"
relm = "^0.19.0"
relm-derive = "^0.19.0"
gdk = "^0.12.0"
gdk-pixbuf = "^0.8.0"
zip = "0.5.4"
